spring:
  application:
   name: spring-cloud-consul-producer
  cloud:
   consul:
    host: localhost
    port: 8500
    discovery:
      serviceName: service-producer1

server:
  port: 8502



#spring.cloud.consul.port=8500
#  #注册到consul的服务名称
#spring.cloud.consul.discovery.serviceName=service-producer
