server:
  port: 8111

spring:
  application:
    name: goods-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true


dubbo:
  scan:
    base-packages: com.luo.nacos
  protocol:
    name: dubbo
    port: 28889
  application:
    name: goods-provider
  registry:
    address: spring-cloud://localhost

